### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by shom13** [adityar224/Random-Face-Generator#1]
Firstly i love the app and the overall concept. Would be great if there was an option to select region, as its more useful to use an image that belongs to a particular region. I do not not know if thats possible, but just a thought to make the app more useful.

**Comment by adityar224** [comment]
Hey thanks for the feedback. I do agree choosing a region would be cool but unfortunately the Api doesn't support that yet and I don't think there is a way to identify a region of a person based on their face at the time being.
