### ISSUE TITLE
Random (Horror) Face Generator

### ISSUE THREAD

**Issue by shivagnihotri** [adityar224/Random-Face-Generator#11]
**Describe the bug**
Faces that are being additionally generated look like diaabled people or even monsters. 😱

**To Reproduce**
1. Generate random face
2. When additional faces ("friends") are being generated, these faces look disabled / monster

**Expected behavior**
Generation of normal faces. Not monsters.

**Screenshots**
If applicable, add screenshots to help explain your problem.![Screenshot_20230402-145443_Random Face Generator.png](https://user-images.githubusercontent.com/97066277/229355062-1d69907b-72fd-4809-909b-4ef0cff72b04.png)

**Smartphone (please complete the following information):**
 - Device: SHIFT6mq
 - OS: Android 12S

**Additional context**
Thanks for having added this app to F-Droid! 🌻

**Comment by adityar224** [comment]
This happens due to extra faces being present in the background (usually the corners) on the original images used to train the algorithm.

You could crop the "monsters" out for now xD.
