### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [adityar224/Random-Face-Generator#2]
Please remember to increase `versionCode` before you make a new release. The current one still shows `versionCode: 1`. As Android uses `versionCode` to tell versions apart, the new release will not be considered an update but the same version, so users won't get any update information.

PS: Any reason why you remove older releases?

**Comment by adityar224** [comment]
Hey I have increased the `version` in `pubspec.yaml` and android definitely considers it as an update. I changed it from `1.0.1` to `1.0.2`. The reason I removed the older release was because the newer one is literally the same thing (apart from the app name and icon) but smaller in size and much better performance.

**Comment by IzzySoft** [comment]
Thanks for your fast reply!

> I changed it from `1.0.1` to `1.0.2`.

That's the `versionName`, sorry. But let me take a look, I have an idea what might be missing in `pubspec.yaml`… Bingo:

```yaml
version: 1.0.2+1
```

That should be

```yaml
version: 1.0.2+2
```

The integer after the `+` sign is the `versionCode` – and that must be increased with each release. The part before (here: `1.0.2`) is just what is shown to the user, and using [semantic versioning](https://semver.org/) as you seem to do, indicates how "heavy" the change was: 1.0.1 => 1.0.2 indicates minor fixes/adjustments/enhancements (details on the linked page).

And no, Android only looks at the `versionCode`. The user still **can** re-install an APK with the same `versionCode` **manually** (no matter what the `versionName` says) – but never a **lower** `versionCode` (again no matter what the `versionName` says). If you have your app in any store that offers automatic update (checks), a user who had 1.0.1 installed will get no notification of the current 1.0.2 being available. You can believe me, I'm [running such a store](https://apt.izzysoft.de/fdroid/repo), and am a maintainer in a [second one](https://f-droid.org/).

----

Thanks for the details on the removed release. I understand this was an exception, and it makes sense. I just was afraid you'd always do that, as there was no 1.0.0 either :rofl: (yes, I've seen such cases in the past).

**Comment by adityar224** [comment]
Thank you so much for your feedback! When I update the app in the near future I would definitely make sure to update the `versionCode` as well. I am also considering deploying the app to F-Droid 😉 so all these tips definitely help.

Also no, I don't plan on removing previous releases from here on out.

**Comment by IzzySoft** [comment]
> I am also considering deploying the app to F-Droid

Great! It's already half-way there (which is how this issue surfaced), [see here](https://apt.izzysoft.de/fdroid/index/apk/com.aditya.random_face_generator) – and be welcome to [add a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to your Readme if you wish :smiley:

If you consider this issue solved (and don't need it as reminder for something), I guess it can be closed then. Thanks a lot!

**Comment by adityar224** [comment]
Thank you soo much! This is great.

**Comment by IzzySoft** [comment]
It won't move to F-Droid.org automatically, though. If you think you're ready for that, you can file an RFP (Request For Packaging) [here](https://gitlab.com/fdroid/rfp/-/issues).

**Comment by yashpalgoyal1304** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2028
