### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by 12people** [adityar224/Random-Face-Generator#5]
I'd love to see this app released for Linux, ideally as a Flatpak.

**Comment by adityar224** [comment]
Working on it 👍

**Comment by 12people** [comment]
Amazing, thanks so much!

I have a bit of experience packaging up Flutter apps as Flatpaks, so if you need some pointers, let me know. :)

**Comment by shuvashish76** [comment]
[AppImage](https://appimage.org/) packaging would be awesome as well. Which is a community project & works on all linux platforms :)
